from django.conf.urls import url, patterns, include

urlpatterns = patterns('accounts.views',
    url(r'^roleplay-test/$', 'roleplay_test', name='roleplay-test'),
    url(r'^login/$', 'accounts_login', name='login'),
    url(r'^logout/$', 'accounts_logout', name='logout'),
    url(r'^register/$', 'accounts_register', name='register'),
    url(r'^friends/', include(patterns('accounts.views',
        url(r'^$', 'friends_index', name='index'),
        url(r'^requests', 'friends_requests', name='requests'),
        url(r'^send_request/(?P<friend_pk>[\d]+)/$',
            'friends_send_request', name='send_request'),
        url(r'^delete_request/(?P<pk>[\d]+)/$', 'friends_delete_request',
            name='delete_request'),
        url(r'^accept_request/(?P<pk>[\d]+)/$', 'friends_accept_request',
            name='accept_request'),
        url(r'^delete_friend/(?P<friend_pk>[\d]+)/$', 'friends_delete_friend',
            name='delete_friend'),
    ), namespace='friends')),
    url(r'^@(?P<slug>[-\w]+)/', include(patterns('accounts.views',
        url(r'^$', 'accounts_profile_index', name='index'),
    ), namespace='profile')),
)
